site_name: NeuroStatX Documentation
repo_url: https://github.com/gagnonanthony/NeuroStatX
repo_name: gagnonanthony/NeuroStatX


theme:
  logo: assets/logo_with_text.png
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: green
      accent: yellow 
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: green
      accent: yellow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized
  - mkapi:
      exclude:
        - neurostatx.tests
      config: config.py

nav:
  - Home: 'index.md'
  - 'CLI Tools': 
    - $api/neurostatx.cli.**
  - 'API Reference':
    - 'neurostatx.clustering': $api/neurostatx.clustering.**
    - 'neurostatx.io': $api/neurostatx.io.**
    - 'neurostatx.network': $api/neurostatx.network.**
    - 'neurostatx.statistics': $api/neurostatx.statistics.**
    - 'neurostatx.utils': $api/neurostatx.utils.**
  - 'About': 
    - 'License': 'license.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gagnonanthony/NeuroStatX.git
  version:
    default: latest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/gagnonanthony"  target="_blank" rel="noopener">Anthony Gagnon</a>